<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Thuan Tran">
<meta name="dcterms.date" content="2025-05-20">

<title>Metaanalysis Assigment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Metaanalysis - Assigment_files/libs/clipboard/clipboard.min.js"></script>
<script src="Metaanalysis - Assigment_files/libs/quarto-html/quarto.js"></script>
<script src="Metaanalysis - Assigment_files/libs/quarto-html/popper.min.js"></script>
<script src="Metaanalysis - Assigment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Metaanalysis - Assigment_files/libs/quarto-html/anchor.min.js"></script>
<link href="Metaanalysis - Assigment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Metaanalysis - Assigment_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Metaanalysis - Assigment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Metaanalysis - Assigment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Metaanalysis - Assigment_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Metaanalysis Assigment</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Thuan Tran </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 20, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#import-the-data" id="toc-import-the-data" class="nav-link active" data-scroll-target="#import-the-data">1. Import the data</a></li>
  <li><a href="#experiment" id="toc-experiment" class="nav-link" data-scroll-target="#experiment">2. Experiment</a>
  <ul class="collapse">
  <li><a href="#a.-combine-the-effects" id="toc-a.-combine-the-effects" class="nav-link" data-scroll-target="#a.-combine-the-effects">a. Combine the effects</a></li>
  <li><a href="#b.-create-a-funnel-plot" id="toc-b.-create-a-funnel-plot" class="nav-link" data-scroll-target="#b.-create-a-funnel-plot">b. Create a funnel plot</a></li>
  <li><a href="#c.-check-if-methods-quality-affect-the-results" id="toc-c.-check-if-methods-quality-affect-the-results" class="nav-link" data-scroll-target="#c.-check-if-methods-quality-affect-the-results">c.&nbsp;Check if methods / quality affect the results</a></li>
  <li><a href="#d.-author-gender" id="toc-d.-author-gender" class="nav-link" data-scroll-target="#d.-author-gender">d.&nbsp;Author Gender</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="import-the-data" class="level2">
<h2 class="anchored" data-anchor-id="import-the-data">1. Import the data</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 28
  Study            `Female authors` `Male authors` `Age (months)` N_boys N_girls
  &lt;chr&gt;                       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1 Alexander &amp; Sae…                2              0           19.5     47      47
2 Arthur (2014)                   1              0           19       22      18
3 Berenbaum &amp; Hin…                2              0           65.8     18      18
4 Berenbaum &amp; Sny…                2              0           93.1     19      19
5 Doering et al (…                1              3           87       15      15
6 Idle et al. (19…                2              1           46       10      10
# ℹ 22 more variables: Mean_boys_play_male &lt;dbl&gt;, SD_boys_play_male &lt;dbl&gt;,
#   Mean_girls_play_male &lt;dbl&gt;, SD_girls_play_male &lt;dbl&gt;,
#   Mean_boys_play_female &lt;dbl&gt;, SD_boys_play_female &lt;dbl&gt;,
#   Mean_girls_play_female &lt;dbl&gt;, SD_girls_play_female &lt;dbl&gt;,
#   `Neutral toys` &lt;dbl&gt;, Year &lt;dbl&gt;, `Parent present` &lt;dbl&gt;, Setting &lt;dbl&gt;,
#   Country &lt;dbl&gt;, `Case definition adequate` &lt;chr&gt;,
#   `Representativeness of cases` &lt;chr&gt;, `Selection of controls` &lt;chr&gt;, …</code></pre>
</div>
</div>
</section>
<section id="experiment" class="level2">
<h2 class="anchored" data-anchor-id="experiment">2. Experiment</h2>
<section id="a.-combine-the-effects" class="level3">
<h3 class="anchored" data-anchor-id="a.-combine-the-effects">a. Combine the effects</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                        SMD            95%-CI %W(random)
Alexander &amp; Saenz (2012)             1.1517 [ 0.7138; 1.5895]        4.4
Arthur (2014)                        1.0747 [ 0.4044; 1.7449]        3.6
Berenbaum &amp; Hines (1992)             0.7796 [ 0.0992; 1.4601]        3.5
Berenbaum &amp; Snyder (1995)            1.7761 [ 1.0137; 2.5385]        3.3
Doering et al (1989)                 1.8261 [ 0.9565; 2.6956]        2.9
Idle et al. (1993)                   0.8469 [-0.0767; 1.7704]        2.8
Lamminmäki &amp; Hines (2012)            0.2310 [-0.3761; 0.8380]        3.8
Li &amp; Wong (2016)                     1.5212 [ 1.0077; 2.0347]        4.1
Pasterski et al. (2005)              2.7109 [ 1.5546; 3.8671]        2.2
Pasterski et al. (2005)              0.7889 [ 0.2117; 1.3661]        3.9
Pasterski et al. (2005)              2.0750 [ 1.3630; 2.7871]        3.4
Schau et al. (1980)                  1.3356 [ 0.7302; 1.9410]        3.8
Servin et al. (1999)                 0.7325 [ 0.0733; 1.3916]        3.6
Servin et al. (1999)                 1.8728 [ 0.9275; 2.8182]        2.7
Servin et al. (1999)                 0.7954 [ 0.0215; 1.5692]        3.2
Todd et al. (2016)                   1.1449 [ 0.4715; 1.8184]        3.6
Todd et al. (2016)                   1.3868 [ 0.6510; 2.1226]        3.3
Todd et al. (2016)                   2.5204 [ 1.5655; 3.4754]        2.7
van de Beek (2009)                   0.5340 [ 0.1784; 0.8896]        4.7
Wilansky-Traynor &amp; Lobel (2008)      1.0374 [ 0.4558; 1.6191]        3.9
Wilansky-Traynor &amp; Lobel (2008)      0.5824 [ 0.0735; 1.0914]        4.1
Zosuls et al. (2009)                 0.6062 [ 0.1331; 1.0792]        4.3
Zosuls et al. (2009)                 0.5527 [ 0.0816; 1.0239]        4.3
Zosuls et al. (2009)                 0.1681 [-0.2947; 0.6309]        4.3
Zosuls et al. (2009)                 0.3929 [-0.0738; 0.8595]        4.3
Zosuls, Ruble &amp; Tamis-LeMonda (2014) 0.6893 [ 0.3978; 0.9807]        4.8
Zosuls, Ruble &amp; Tamis-LeMonda (2014) 0.5288 [ 0.1899; 0.8676]        4.7

Number of studies: k = 27
Number of observations: o = 1610 (o.e = 797, o.c = 813)

                        SMD           95%-CI    z  p-value
Random effects model 1.0109 [0.7893; 1.2324] 8.94 &lt; 0.0001

Quantifying heterogeneity (with 95%-CIs):
 tau^2 = 0.2415 [0.1249; 0.6735]; tau = 0.4914 [0.3535; 0.8207]
 I^2 = 71.1% [57.5%; 80.4%]; H = 1.86 [1.53; 2.26]

Test of heterogeneity:
     Q d.f.  p-value
 90.05   26 &lt; 0.0001

Details of meta-analysis methods:
- Inverse variance method
- Restricted maximum-likelihood estimator for tau^2
- Q-Profile method for confidence interval of tau^2 and tau
- Calculation of I^2 based on Q
- Hedges' g (bias corrected standardised mean difference; using exact formulae)</code></pre>
</div>
</div>
<p>We can see that:</p>
<ul>
<li><p>27 studies were included.</p></li>
<li><p>the overall effect size (SMD) is 1.01 with a 95% confidence interval of [0.79; 1.23].</p></li>
<li><p>This means boys played significantly more with male-typed toys than girls did.</p></li>
<li><p>The p-value &lt; 0.0001, showing a statistically significant difference.</p></li>
<li><p>Heterogeneity is high:</p>
<ul>
<li><p>I² = 71.1%, meaning much of the variation is due to differences between studies.</p></li>
<li><p>Tau² = 0.24, indicating moderate variability in effect sizes.</p></li>
</ul></li>
</ul>
</section>
<section id="b.-create-a-funnel-plot" class="level3">
<h3 class="anchored" data-anchor-id="b.-create-a-funnel-plot">b. Create a funnel plot</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Metaanalysis---Assigment_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can observe that:</p>
<ul>
<li><p>the plot is slightly skewed, with more studies appearing on the right side.</p></li>
<li><p>This may suggest a possible publication bias: studies showing stronger effects (in favor of boys preferring male-typed toys) may be more likely to be published.</p></li>
<li><p>However, the distribution is not extremely asymmetric, so the bias may be small.</p></li>
</ul>
</section>
<section id="c.-check-if-methods-quality-affect-the-results" class="level3">
<h3 class="anchored" data-anchor-id="c.-check-if-methods-quality-affect-the-results">c.&nbsp;Check if methods / quality affect the results</h3>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in find(i): elements of 'what' after the first will be ignored
Warning in find(i): elements of 'what' after the first will be ignored
Warning in find(i): elements of 'what' after the first will be ignored</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in formula.character(object, env = baseenv()): Using formula(x) is deprecated when x is a character vector of length &gt; 1.
  Consider formula(paste(x, collapse = " ")) instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 1 study with NAs omitted from model fitting.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Redundant predictors dropped from the model.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 26; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.2160 (SE = 0.1198)
tau (square root of estimated tau^2 value):             0.4648
I^2 (residual heterogeneity / unaccounted variability): 72.47%
H^2 (unaccounted variability / sampling variability):   3.63
R^2 (amount of heterogeneity accounted for):            9.78%

Test for Residual Heterogeneity:
QE(df = 14) = 42.6865, p-val &lt; .0001

Test of Moderators (coefficients 2:12):
QM(df = 11) = 13.9329, p-val = 0.2367

Model Results:

                          estimate      se     zval    pval     ci.lb    ci.ub 
intrcpt                    13.3207  5.1865   2.5684  0.0102    3.1555  23.4860 
`Neutral toys`             -1.8133  0.7566  -2.3965  0.0166   -3.2962  -0.3303 
`Parent present`           -0.0882  0.2196  -0.4018  0.6879   -0.5186   0.3422 
Setting                    -2.3343  0.9257  -2.5216  0.0117   -4.1486  -0.5199 
Country                   -12.9688  4.6177  -2.8085  0.0050  -22.0193  -3.9183 
Quality_CaseDef             0.3219  0.6448   0.4993  0.6176   -0.9418   1.5857 
Quality_Represent           0.3791  0.4284   0.8849  0.3762   -0.4605   1.2187 
Quality_Controls           -1.5056  0.6490  -2.3200  0.0203   -2.7777  -0.2336 
Quality_ParentOpinion       1.2270  0.4143   2.9617  0.0031    0.4150   2.0390 
Quality_ComparableGroups   -2.0142  1.2090  -1.6659  0.0957   -4.3838   0.3555 
Quality_BehaviourDefined   -0.7010  0.6665  -1.0517  0.2929   -2.0073   0.6054 
Quality_Nonresponse        -1.2859  0.5108  -2.5175  0.0118   -2.2871  -0.2848 
                             
intrcpt                    * 
`Neutral toys`             * 
`Parent present`             
Setting                    * 
Country                   ** 
Quality_CaseDef              
Quality_Represent            
Quality_Controls           * 
Quality_ParentOpinion     ** 
Quality_ComparableGroups   . 
Quality_BehaviourDefined     
Quality_Nonresponse        * 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>We ran a model to see if the way studies were done (methods and quality) affected the results.</li>
<li>These things did make a difference:
<ul>
<li>Not using neutral toys → stronger results.</li>
<li>Study setting (home, lab, nursery) affected results.</li>
<li>Countries with more gender equality had smaller effects.</li>
<li>Studies that matched boys and girls well showed different results.</li>
<li>Asking parents about gender views made results stronger.</li>
<li>Reporting dropouts also affected results.</li>
<li>The model explained about 10% of the differences between studies.</li>
<li>There is still a lot of variation (I² = 72%) that is not explained.</li>
</ul></li>
</ul>
<p><em>About the warnings:</em></p>
<ul>
<li><p>One study was skipped because of missing data.</p></li>
<li><p>Some variables were removed automatically because they didn’t help the model.</p></li>
</ul>
</section>
<section id="d.-author-gender" class="level3">
<h3 class="anchored" data-anchor-id="d.-author-gender">d.&nbsp;Author Gender</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 27; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.1873 (SE = 0.0798)
tau (square root of estimated tau^2 value):             0.4327
I^2 (residual heterogeneity / unaccounted variability): 70.92%
H^2 (unaccounted variability / sampling variability):   3.44
R^2 (amount of heterogeneity accounted for):            22.46%

Test for Residual Heterogeneity:
QE(df = 25) = 75.5636, p-val &lt; .0001

Test of Moderators (coefficient 2):
QM(df = 1) = 6.4226, p-val = 0.0113

Model Results:

                 estimate      se     zval    pval    ci.lb    ci.ub      
intrcpt            1.7059  0.2981   5.7226  &lt;.0001   1.1216   2.2901  *** 
Majority_Female   -0.8055  0.3178  -2.5343  0.0113  -1.4284  -0.1825    * 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p>We tested if the gender of the study authorsaffected the results.</p></li>
<li><p>Specifically, we looked at whether studies with more female authors gave different results.</p></li>
</ul>
<p>What we found:</p>
<ul>
<li><p>Studies with more female authors showed a smaller effect size.</p></li>
<li><p>The difference was statistically significant (p = 0.011).</p></li>
<li><p>This means author gender may influence the reported outcomes.</p></li>
<li><p>The model explained about 22% of the variation between studies.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>